### ISSUE TITLE
build faiils

### ISSUE THREAD

**Issue by lukaszkaleta** [leoterry-ulrica/wopi-demo#1]
[ERROR] Failed to execute goal on project wopi-demo: Could not resolve dependencies for project com.weifj.wopi:wopi-demo:war:1.0.0-SNAPSHOT: The following artifacts could not be resolved: com.ibm.filenet:jace:jar:1.0.0, com.ibm.xml:xlxpScannerUtils:jar:1.1.19, com.ibm.xml:xlxpScanner:jar:1.1.19: Could not find artifact com.ibm.filenet:jace:jar:1.0.0 in central (http://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by leoterry-ulrica** [comment]
sorry, this is a jar in my private repository.
